# Generated by Django 3.1.5 on 2021-03-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follow',
        ),
    ]
